import type { GameMap, MapId, Terrain } from './types';

/**
 * The seven maps of 寶咖咖奇俠傳, one per chapter. Grids are drawn as text so a map can be
 * read at a glance; validate.ts checks row lengths, exits, NPC positions and reachability.
 *
 *   #  wall     f  fence    D  door (walk onto it to leave)    ~  water
 *   .  floor    r  rug      t  tile     g  grass     p  path    s  sand
 *   c  cobble   d  dark     b  blanket (棉被山)
 */
const LEGEND: Record<string, Terrain> = {
  '#': 'wall',
  f: 'fence',
  D: 'door',
  '~': 'water',
  '.': 'floor',
  r: 'rug',
  t: 'tile',
  g: 'grass',
  p: 'path',
  s: 'sand',
  c: 'cobble',
  d: 'dark',
  b: 'blanket',
  ' ': 'void',
};

export const MAPS: Record<MapId, GameMap> = {
  home: {
    id: 'home',
    chapter: 1,
    title: '客廳',
    palette: 'living',
    legend: LEGEND,
    grid: [
      '######D#######',
      '#............#',
      '#..rrrrr.....#',
      '#..rrrrr.....#',
      '#..rrrrr.....#',
      '#............#',
      'D............#',
      '#............#',
      '#............#',
      '#............#',
      '######D#######',
    ],
    entry: { c: 6, r: 5 },
    decor: [
      { sprite: 'sofa', c: 3, r: 1, w: 2, size: 1.6 },
      { sprite: 'coffeeTable', c: 5, r: 3, size: 1.1 },
      { sprite: 'floorLamp', c: 1, r: 1, size: 2 },
      { sprite: 'pottedPlant', c: 12, r: 1, size: 1.5 },
      { sprite: 'wallClock', c: 9, r: 1, size: 1, solid: false },
      { sprite: 'slipper', c: 11, r: 8, size: 0.8, solid: false },
    ],
    npcs: [
      {
        id: 'mom',
        name: '媽媽',
        sprite: 'mom',
        c: 9,
        r: 3,
        flip: true,
        talk: [
          { when: 'octopusDone', event: 'home.mom.night' },
          { when: 'mochaJoined', event: 'home.mom.hug' },
          { event: 'home.mom.first' },
        ],
      },
      {
        id: 'grandma',
        name: '阿嬤',
        sprite: 'grandma',
        c: 2,
        r: 8,
        talk: [{ when: 'grandmaGave', event: 'home.grandma.again' }, { event: 'home.grandma.first' }],
      },
      { id: 'mochaNpc', name: '摩卡貓', sprite: 'mochaCat', c: 5, r: 1, not: 'mochaJoined', talk: [{ event: 'home.mocha' }] },
      { id: 'dust', name: '灰塵球', sprite: 'dustBunny', c: 6, r: 9, not: 'dustDone', talk: [{ event: 'home.dust' }] },
      { id: 'dad', name: '爸爸', sprite: 'dad', c: 11, r: 5, talk: [{ event: 'home.dad' }] },
    ],
    chests: [{ id: 'home-book', c: 12, r: 9, item: 'clothBook' }],
    exits: [
      { c: 6, r: 10, to: 'yard', at: { c: 8, r: 1 } },
      { c: 0, r: 6, to: 'bath', at: { c: 1, r: 5 }, when: 'fishDone', blocked: 'home.bathDoor' },
      { c: 6, r: 0, to: 'night', at: { c: 7, r: 12 }, when: 'octopusDone', blocked: 'home.bedDoor' },
    ],
    triggers: [{ id: 'home-intro', c: 6, r: 5, event: 'home.intro', once: true }],
  },

  yard: {
    id: 'yard',
    chapter: 2,
    title: '院子',
    palette: 'yard',
    legend: LEGEND,
    grid: [
      'ffffffffDfffffffff',
      'fgggggggpggggggggf',
      'fgggggggpggggggggf',
      'fgggggggppppppgggf',
      'fggggggggggggpgggf',
      'fggggggggggggpgggf',
      'fggggggggggggppppf',
      'fgggggggggggggggpf',
      'fgggggggggggggggpf',
      'fgggggggggggggggpf',
      'fgggggggggggggggpf',
      'fgggggggggggggggpf',
      'fgggggggggggggggpf',
      'ffffffffffffffffDf',
    ],
    entry: { c: 8, r: 1 },
    decor: [
      { sprite: 'tree', c: 3, r: 3, size: 2.4 },
      { sprite: 'tree', c: 13, r: 9, size: 2.4 },
      { sprite: 'tree', c: 6, r: 11, size: 2.2 },
      { sprite: 'flowerPot', c: 2, r: 11, size: 0.9 },
      { sprite: 'flowerPot', c: 4, r: 11, size: 0.9 },
      { sprite: 'stone', c: 9, r: 8, size: 0.8 },
      { sprite: 'wateringCan', c: 14, r: 2, size: 0.9 },
      { sprite: 'butterfly', c: 6, r: 6, size: 0.7, solid: false },
    ],
    npcs: [
      { id: 'dog', name: '小狗', sprite: 'dog', c: 10, r: 4, talk: [{ when: 'golemDone', event: 'yard.dog.after' }, { event: 'yard.dog' }] },
      { id: 'golem', name: '積木巨人', sprite: 'blockGolem', c: 16, r: 12, not: 'golemDone', talk: [{ event: 'yard.golem' }] },
    ],
    chests: [{ id: 'yard-cookies', c: 2, r: 2, item: 'cookie', count: 2 }],
    exits: [
      { c: 8, r: 0, to: 'home', at: { c: 6, r: 9 } },
      { c: 16, r: 13, to: 'park', at: { c: 1, r: 7 } },
    ],
    triggers: [{ id: 'yard-intro', c: 8, r: 1, event: 'yard.intro', once: true }],
    encounters: {
      groups: [['dustBunny', 'dustBunny'], ['sockMonster'], ['mosquito', 'mosquito'], ['snail'], ['mosquito', 'dustBunny'], ['snail', 'mosquito']],
      rate: 0.14,
      min: 4,
      zone: { c0: 1, r0: 3, c1: 16, r1: 12 },
    },
  },

  park: {
    id: 'park',
    chapter: 3,
    title: '公園',
    palette: 'park',
    legend: LEGEND,
    grid: [
      'ffffffffffffffffffffff',
      'fggggggggggggggggggggf',
      'fggggggggggggggggggggf',
      'fggggggggggggggggggggf',
      'fggggggggggggggggggggf',
      'fggggggggggggggggggggf',
      'fgggggggpppppppppppggf',
      'Dppppppppgggggggggpggf',
      'fgggggggggggggggggpppD',
      'fggggggggggggggggggggf',
      'fggggggggggggggggggggf',
      'fggggggggggggggggggggf',
      'fggggggggggggggggggggf',
      'fggggggggggggggggggggf',
      'fggggggggggggggggggggf',
      'ffffffffffffffffffffff',
    ],
    entry: { c: 1, r: 7 },
    decor: [
      { sprite: 'bench', c: 3, r: 4, w: 2, size: 1.3 },
      { sprite: 'slide', c: 4, r: 10, w: 2, size: 1.8 },
      { sprite: 'napMat', c: 3, r: 12, size: 1.2, solid: false },
      { sprite: 'crate', c: 7, r: 3, size: 1 },
      { sprite: 'tree', c: 12, r: 3, size: 2.4 },
      { sprite: 'tree', c: 15, r: 10, size: 2.4 },
      { sprite: 'tree', c: 18, r: 4, size: 2.2 },
      { sprite: 'tree', c: 12, r: 12, size: 2.4 },
      { sprite: 'kite', c: 17, r: 7, size: 1.2, solid: false },
      { sprite: 'bird', c: 9, r: 2, size: 0.6, solid: false },
      { sprite: 'signpost', c: 9, r: 8, size: 1.1 },
    ],
    npcs: [
      { id: 'mom', name: '媽媽', sprite: 'mom', c: 2, r: 12, talk: [{ event: 'park.mom' }] },
      { id: 'uncle', name: '冰阿伯', sprite: 'uncle', c: 6, r: 3, talk: [{ event: 'park.uncle' }] },
      { id: 'kid', name: '小花', sprite: 'kid', c: 8, r: 9, flip: true, talk: [{ when: 'crowDone', event: 'park.kid.after' }, { event: 'park.kid' }] },
      { id: 'crow', name: '烏鴉老大', sprite: 'crowBoss', c: 20, r: 8, not: 'crowDone', talk: [{ event: 'park.crow' }] },
    ],
    chests: [{ id: 'park-purse', c: 20, r: 2, item: 'coinPurse' }],
    exits: [
      { c: 0, r: 7, to: 'yard', at: { c: 16, r: 12 } },
      { c: 21, r: 8, to: 'market', at: { c: 1, r: 7 } },
    ],
    triggers: [{ id: 'park-intro', c: 1, r: 7, event: 'park.intro', once: true }],
    encounters: {
      groups: [['pigeon', 'pigeon'], ['kiteGhost'], ['kiteGhost', 'pigeon'], ['pigeon', 'pigeon', 'pigeon'], ['moleKing'], ['kiteGhost', 'kiteGhost']],
      rate: 0.13,
      min: 4,
      zone: { c0: 11, r0: 1, c1: 20, r1: 14 },
    },
  },

  market: {
    id: 'market',
    chapter: 4,
    title: '市場',
    palette: 'market',
    legend: LEGEND,
    grid: [
      '####################',
      '#cccccccccccccccccc#',
      '#cccccccccccccccccc#',
      '#cccccccccccccccccc#',
      '#cccccccccccccccccc#',
      '#cccccccccccccccccc#',
      '#cccccccccccccccccc#',
      'Dcccccccccccccccccc#',
      '#cccccccccccccccccc#',
      '#cccccccccccccccccc#',
      '#cccccccccccccccccc#',
      '#cccccccccccccccccc#',
      '#cccccccccccccccccc#',
      '####################',
    ],
    entry: { c: 1, r: 7 },
    decor: [
      { sprite: 'awning', c: 3, r: 1, w: 3, size: 1.6 },
      { sprite: 'crate', c: 3, r: 4, size: 1 },
      { sprite: 'crate', c: 5, r: 4, size: 1 },
      { sprite: 'lantern', c: 9, r: 1, size: 1.2, solid: false },
      { sprite: 'lantern', c: 14, r: 1, size: 1.2, solid: false },
      { sprite: 'scale', c: 10, r: 5, size: 1 },
      { sprite: 'fishStall', c: 14, r: 2, w: 2, size: 1.7 },
      { sprite: 'crate', c: 12, r: 9, size: 1 },
      { sprite: 'apple', c: 7, r: 11, size: 0.6, solid: false },
      { sprite: 'crate', c: 16, r: 11, size: 1 },
    ],
    npcs: [
      { id: 'vendor', name: '老闆娘', sprite: 'vendor', c: 4, r: 3, talk: [{ event: 'market.vendor' }] },
      { id: 'uncle', name: '豆花阿伯', sprite: 'uncle', c: 11, r: 9, talk: [{ event: 'market.uncle' }] },
      { id: 'kid', name: '小花', sprite: 'kid', c: 8, r: 11, talk: [{ event: 'market.kid' }] },
      { id: 'fish', name: '大魚', sprite: 'bigFish', c: 15, r: 4, not: 'fishDone', talk: [{ event: 'market.fish' }] },
    ],
    chests: [{ id: 'market-fish', c: 17, r: 11, item: 'driedFish', count: 2 }],
    exits: [{ c: 0, r: 7, to: 'park', at: { c: 20, r: 8 } }],
    triggers: [{ id: 'market-intro', c: 1, r: 7, event: 'market.intro', once: true }],
    encounters: {
      groups: [['crab'], ['rollingApple', 'rollingApple'], ['crab', 'rollingApple'], ['crab', 'crab'], ['rollingApple', 'rollingApple', 'rollingApple']],
      rate: 0.12,
      min: 5,
      zone: { c0: 8, r0: 5, c1: 18, r1: 12 },
    },
  },

  bath: {
    id: 'bath',
    chapter: 5,
    title: '浴缸島',
    palette: 'living',
    legend: LEGEND,
    grid: [
      '############',
      '#tttttttttt#',
      '#tttttttttt#',
      '#tttttttttt#',
      '#tttttttttt#',
      'DttttttttttD',
      '#tttttttttt#',
      '#tttttttttt#',
      '#tttttttttt#',
      '############',
    ],
    entry: { c: 1, r: 5 },
    decor: [
      { sprite: 'bathtub', c: 5, r: 3, w: 2, h: 2, size: 2.4 },
      { sprite: 'bucket', c: 2, r: 7, size: 0.9 },
      { sprite: 'toyBoat', c: 9, r: 2, size: 0.8, solid: false },
    ],
    npcs: [{ id: 'duckNpc', name: '小鴨鴨', sprite: 'duck', c: 8, r: 5, flip: true, not: 'duckJoined', talk: [{ event: 'bath.duck' }] }],
    chests: [{ id: 'bath-boat', c: 2, r: 2, item: 'toyBoat' }],
    exits: [
      { c: 0, r: 5, to: 'home', at: { c: 1, r: 6 } },
      { c: 11, r: 5, to: 'beach', at: { c: 1, r: 6 }, when: 'duckJoined', blocked: 'bath.notYet' },
    ],
    triggers: [{ id: 'bath-intro', c: 1, r: 5, event: 'bath.intro', once: true }],
  },

  beach: {
    id: 'beach',
    chapter: 6,
    title: '海邊',
    palette: 'beach',
    legend: LEGEND,
    grid: [
      'ffffffffffffffffffffff',
      'fssssssssssssssssssssf',
      'fssssssssssssssssssssf',
      'fssssssssssssssssssssf',
      'fssssssssssssssssssssf',
      'fssssssssssssssssssssf',
      'Dssssssssssssssssssssf',
      'fssssssssssssssssssssf',
      'fssssssssssssssssssssf',
      '~~~~~~~~~~~~~~~~~~~~~~',
      '~~~~~~~~~~~~~~~~~~~~~~',
      '~~~~~~~~~~~~~~~~~~~~~~',
    ],
    entry: { c: 1, r: 6 },
    decor: [
      { sprite: 'beachUmbrella', c: 4, r: 3, size: 2 },
      { sprite: 'sandcastle', c: 8, r: 7, size: 1.2 },
      { sprite: 'starfish', c: 12, r: 8, size: 0.6, solid: false },
      { sprite: 'shell', c: 3, r: 7, size: 0.5, solid: false },
      { sprite: 'seagull', c: 16, r: 2, size: 0.8, solid: false },
      { sprite: 'beachUmbrella', c: 14, r: 4, size: 2, flip: true },
      { sprite: 'crate', c: 2, r: 2, size: 1 },
    ],
    npcs: [
      { id: 'vendor', name: '老闆娘', sprite: 'vendor', c: 3, r: 2, talk: [{ event: 'beach.vendor' }] },
      { id: 'octo', name: '大章魚', sprite: 'octopus', c: 19, r: 7, not: 'octopusDone', talk: [{ event: 'beach.octo' }] },
    ],
    chests: [{ id: 'beach-star', c: 20, r: 2, item: 'star' }],
    exits: [{ c: 0, r: 6, to: 'bath', at: { c: 10, r: 5 } }],
    triggers: [{ id: 'beach-intro', c: 1, r: 6, event: 'beach.intro', once: true }],
    encounters: {
      groups: [['greedyGull'], ['jellyfish'], ['greedyGull', 'greedyGull'], ['jellyfish', 'greedyGull'], ['jellyfish', 'jellyfish'], ['greedyGull', 'greedyGull', 'jellyfish']],
      rate: 0.13,
      min: 5,
      zone: { c0: 6, r0: 1, c1: 18, r1: 8 },
    },
  },

  night: {
    id: 'night',
    chapter: 7,
    title: '棉被山',
    palette: 'night',
    legend: LEGEND,
    grid: [
      '################',
      '#dddddddddddddd#',
      '#dddddddddddddd#',
      '#ddddddbbbddddd#',
      '#dddddbbbbbdddd#',
      '#ddddbbbbbbbddd#',
      '#dddbbbbbbbbbdd#',
      '#ddddbbbbbbbddd#',
      '#dddddbbbbbdddd#',
      '#ddddddbbbddddd#',
      '#dddddddddddddd#',
      '#dddddddddddddd#',
      '#dddddddddddddd#',
      '#######D########',
    ],
    entry: { c: 7, r: 12 },
    decor: [
      { sprite: 'bed', c: 12, r: 1, w: 2, h: 2, size: 2.4 },
      { sprite: 'moonWindow', c: 4, r: 1, size: 1.6, solid: false },
      { sprite: 'pillow', c: 2, r: 5, size: 0.9 },
      { sprite: 'blanket', c: 3, r: 10, size: 1.1 },
      { sprite: 'star', c: 8, r: 2, size: 0.5, solid: false },
      { sprite: 'star', c: 11, r: 8, size: 0.5, solid: false },
      { sprite: 'star', c: 4, r: 8, size: 0.4, solid: false },
    ],
    npcs: [
      { id: 'snore', name: '打呼嚕大王', sprite: 'snoreKing', c: 12, r: 4, not: 'snoreDone', talk: [{ event: 'night.boss' }] },
    ],
    chests: [
      { id: 'night-lamp', c: 2, r: 11, item: 'nightLight' },
      { id: 'night-banana', c: 14, r: 11, item: 'banana' },
    ],
    exits: [{ c: 7, r: 13, to: 'home', at: { c: 6, r: 1 } }],
    triggers: [{ id: 'night-intro', c: 7, r: 12, event: 'night.intro', once: true }],
    encounters: {
      groups: [['sleepySprite'], ['sleepySprite', 'sleepySprite'], ['nightmareCloud'], ['nightmareCloud', 'sleepySprite'], ['nightmareCloud', 'nightmareCloud']],
      rate: 0.13,
      min: 4,
      zone: { c0: 1, r0: 1, c1: 14, r1: 10 },
    },
  },
};

export const MAP_ORDER: readonly MapId[] = ['home', 'yard', 'park', 'market', 'bath', 'beach', 'night'];

export const CHAPTER_TITLES: readonly string[] = [
  '娃娃不見了',
  '院子大冒險',
  '公園的午後',
  '熱鬧的市場',
  '浴缸島',
  '海邊的大章魚',
  '棉被山之巔',
];
